-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 21:46:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SQL_MMO_Entity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SQL_MMO_Entity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SQL_MMO_Entity` DEFAULT CHARACTER SET utf8mb4 ;
USE `SQL_MMO_Entity` ;

-- -----------------------------------------------------
-- Table `SQL_MMO_Entity`.`DBUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SQL_MMO_Entity`.`DBUser` (
  `UID` BIGINT UNSIGNED NOT NULL,
  `UserName` VARCHAR(16) NOT NULL,
  `Password` VARCHAR(60) NOT NULL,
  `RegistrationTime` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`UID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
